// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApfh-NXULF7l2f3qNQNUjh788R6pBx0LU',
    appId: '1:1059886225476:web:751e5541e677de7e7d0411',
    messagingSenderId: '1059886225476',
    projectId: 'zink-e5b99',
    authDomain: 'zink-e5b99.firebaseapp.com',
    storageBucket: 'zink-e5b99.firebasestorage.app',
    measurementId: 'G-Y1JB721MMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTbG4Dhku0gkIYFTL8BNT_aIM8etcogwA',
    appId: '1:1059886225476:android:d1339212bd0160f47d0411',
    messagingSenderId: '1059886225476',
    projectId: 'zink-e5b99',
    storageBucket: 'zink-e5b99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo76P-BEcEW9KLmcbpQLYnpdxdjcH9mgA',
    appId: '1:1059886225476:ios:42134ea9a117fcb87d0411',
    messagingSenderId: '1059886225476',
    projectId: 'zink-e5b99',
    storageBucket: 'zink-e5b99.firebasestorage.app',
    iosBundleId: 'com.example.zink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo76P-BEcEW9KLmcbpQLYnpdxdjcH9mgA',
    appId: '1:1059886225476:ios:42134ea9a117fcb87d0411',
    messagingSenderId: '1059886225476',
    projectId: 'zink-e5b99',
    storageBucket: 'zink-e5b99.firebasestorage.app',
    iosBundleId: 'com.example.zink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApfh-NXULF7l2f3qNQNUjh788R6pBx0LU',
    appId: '1:1059886225476:web:f513a4a97784bda37d0411',
    messagingSenderId: '1059886225476',
    projectId: 'zink-e5b99',
    authDomain: 'zink-e5b99.firebaseapp.com',
    storageBucket: 'zink-e5b99.firebasestorage.app',
    measurementId: 'G-PM2P6RCFJE',
  );
}
